spring:
  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  
  jpa:
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false

logging:
  level:
    com.stockanalyzer: INFO
    org.springframework.web: WARN
