server:
  port: 8080
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/stock_analyzer
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    com.stockanalyzer: INFO
    org.springframework.web: WARN
