CREATE TABLE IF NOT EXISTS technical_indicators (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    calculation_date DATE NOT NULL,
    rsi_14 DECIMAL(5,2),
    ema_9 DECIMAL(12,2),
    ema_21 DECIMAL(12,2),
    sma_20 DECIMAL(12,2),
    atr_14 DECIMAL(8,4),
    vwap DECIMAL(12,2),
    volume_sma_20 BIGINT,
    volume_ratio DECIMAL(6,3),
    price_strength DECIMAL(8,4),
    volume_strength DECIMAL(8,4),
    delivery_strength DECIMAL(8,4),
    macd DECIMAL(8,4),
    macd_signal DECIMAL(8,4),
    macd_histogram DECIMAL(8,4),
    bollinger_upper DECIMAL(12,2),
    bollinger_lower DECIMAL(12,2),
    bollinger_width DECIMAL(8,4),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_symbol_calc_date (symbol, calculation_date),
    INDEX idx_calculation_date (calculation_date),
    INDEX idx_volume_ratio (volume_ratio DESC),
    CONSTRAINT fk_indicators_symbol FOREIGN KEY (symbol) REFERENCES stocks(symbol) ON DELETE CASCADE
);
