CREATE TABLE IF NOT EXISTS btst_analysis (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    analysis_date DATE NOT NULL,
    had_late_surge BOOLEAN,
    late_session_volume_ratio DECIMAL(8,4),
    breakout_level DECIMAL(12,2),
    had_catalyst BOOLEAN,
    catalyst_type VARCHAR(100),
    gap_percentage DECIMAL(8,4),
    shows_absorption BOOLEAN,
    average_trade_size DECIMAL(12,2),
    retail_intensity DECIMAL(5,2),
    vwap_reclaimed BOOLEAN,
    cumulative_delta DECIMAL(12,4),
    pullback_depth DECIMAL(12,4),
    supply_exhaustion BOOLEAN,
    strength_score DECIMAL(12,4),
    recommendation VARCHAR(20),
    confidence_score DECIMAL(12,4),
    entry_price DECIMAL(12,2),
    target_price DECIMAL(12,2),
    stop_loss DECIMAL(12,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_symbol_analysis_date (symbol, analysis_date),
    INDEX idx_analysis_date (analysis_date),
    INDEX idx_recommendation (recommendation),
    INDEX idx_confidence_score (confidence_score DESC),
    INDEX idx_strength_score (strength_score DESC),
    CONSTRAINT fk_btst_symbol FOREIGN KEY (symbol) REFERENCES stocks(symbol) ON DELETE CASCADE
);
