server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: stock-analyzer
  profiles:
    active: dev
  
  datasource:
    url: jdbc:mysql://localhost:3307/stock_analyzer?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:interOP@123}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL

# 5paisa Configuration
fivepaisa:
  api:
    base-url: "https://openapi.5paisa.com/VendorsAPI/Service1.svc"
    app-name: ${FIVEPAISA_APP_NAME:YOUR_APP_NAME}
    app-version: "1.0"
    os-name: "WEB"
    encrypt-key: ${FIVEPAISA_ENCRYPT_KEY:YOUR_ENCRYPT_KEY}
    user-key: ${FIVEPAISA_USER_KEY:YOUR_USER_KEY}
    user-id: ${FIVEPAISA_USER_ID:YOUR_USER_ID}
    password: ${FIVEPAISA_PASSWORD:YOUR_PASSWORD}
    login-id: ${FIVEPAISA_CLIENT_CODE:YOUR_CLIENT_CODE}
    client-code: ${FIVEPAISA_CLIENT_CODE:YOUR_CLIENT_CODE}

# NSE Configuration
nse:
  bhavcopy:
    base-url: "https://nsearchives.nseindia.com/content/cm/"
    file-pattern: "BhavCopy_NSE_CM_0_0_0_{date}_F_0000.csv.zip"
    download-path: "./data/bhavcopy/"
    retry-attempts: 3
    retry-delay: 5000

# Technical Analysis Configuration
technical-analysis:
  indicators:
    rsi-period: 14
    ema-short: 9
    ema-long: 21
    volume-sma: 20
    atr-period: 14
  lookback-days: 100

# BTST Analysis Configuration
btst:
  analysis:
    min-volume: 500000
    min-value: 50000000
    min-price: 10.0
    max-gap-down: -1.5
    min-gap-up: -0.5
    confidence-threshold: 50.0

logging:
  level:
    com.stockanalyzer: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  file:
    name: ./data/logs/stock-analyzer.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
